blank_issues_enabled: false

# Only show specific issue templates
issue_templates:
  - name: Good First Issue
    filename: 01-good_first_issue.yml
  - name: Test
    filename: 02-test.yml
  - name: Live Version
    filename: 03-current-live-version.yml
# Test contact links
contact_links:
  - name: Hiero Discord
    url: https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/discord.md
    about: Please ask and answer questions here.
