name: Enforce Good First Issue Candidate Guard

on:
    issues:
        types:
            - assigned

permissions:
    issues: write
    contents: read

jobs:
    enforce-GFIC:
        runs-on: ubuntu-latest

        concurrency:
            group: GFIC-assign-${{ github.event.issue.number }}
            cancel-in-progress: false

        steps:
            - name: Checkout repository
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - name: Enforce GFIC guard
              uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8.0.0
              with:
                  script: |
                      const script = require('./.github/scripts/bots/reject-good-first-issue-candidates.js');
                      await script({ github, context });
